### ISSUE TITLE
jinhokim: init-ServerConfigInfo

### ISSUE THREAD

**Issue by kimjinho1** [FareWellWebServer/webserv#11]
## description
> ServerConfigInfo 구현
## todo
- [x] 파싱 :파싱 및 에러 처리
- [ ] 메서드 :  파싱 결과를 반환하는 메서드들 구현
 
- [ ] location 경로로 왔을 때, redirection하는 경로로 uri 변경?
- [ ] index가 존재할 경우 index ~ ~ 에 존재하는 파일들을 탐색하도록 경로생성
