### ISSUE TITLE
Silee : Config Info Check

### ISSUE THREAD

**Issue by SihunLee-1016** [FareWellWebServer/webserv#14]
## description
> jinhokim님이 작성하신 코드를 보며 개선해야할 사항을 찾아보고 추가 작성 필요한 부분 작성할 예정입니다.
## todo
- [ ] jinhokim님 코드 읽기
- [ ] 읽고 오류 찾기
- [ ] 부족한 부분 찾아서 추가 작성
