### ISSUE TITLE
haryu: test vector<char> data

### ISSUE THREAD

**Issue by Paul2021-R** [FareWellWebServer/webserv#15]
## description
char * 와 string 을 활용할 경우 HTTP 통신 과정에서 entity 부분에서 데이터 제어 및 읽기가 어려운 문제가 있음. 이를 해결하기 위해 해결 방법으로 vector<char> 를 활용하여 데이터를 기록, 해당 데이터를 출력하는 구조로 했을 시 binary 파일 온전한 읽기 및 출력, 데이터 무결성을 검증한다.
## todo
- [x] test.png 파일을 읽고, vector<char> 로 데이터를 수용하기
- [x] vector<char>로 저장된 데이터 상태에서 vector의 기능 사용에 문제가 없는지 확인하기
- [x] vector<char>로 저장시킨 데이터를 다시 ofstream을 통해 출력하여 데이터 상태가 이상이 없는지 확인
- [x] 선형 구조 방식의 경우 발생할 수 있는 성능적 문제를 해결하기 위해 데이터 입출력 방법에 대해 고려하기
