### ISSUE TITLE
method processor 

### ISSUE THREAD

**Issue by Paul2021-R** [FareWellWebServer/webserv#27]
## description
> Method processor 를 위한 기초 틀 작성하기
## todo
- [ ] 기초 틀 클래스 작성하기 
- [ ] GET 메소드 만들기 (HEAD)
- [ ] POST 메소드 만들기 
- [ ] PUT 메소드 만들기 
- [ ] DELETE 메소드 만들기
- [ ] 테스트 진행하기
