### ISSUE TITLE
Req_Handler_0128

### ISSUE THREAD

**Issue by SihunLee-1016** [FareWellWebServer/webserv#28]
## description
> Request handler 제작.
## todo
- [ ] data 저장할 구조체 or 클래스 생성
- [ ] accept 이후 받아온 socket descripter로 저장
- [ ] 저장된 req msg 요청 라인 / 헤더 / 본문 에 따라 옵션 찾아 저장
