### ISSUE TITLE
Req_Handler 수정 (유효성 검사 및 예외처리)

### ISSUE THREAD

**Issue by SihunLee-1016** [FareWellWebServer/webserv#39]
## description
> Req_Handler 수정 (유효성 검사 및 예외처리)
## todo
- [x] append 시 ctmp로 
- [x] 첫줄이 CRLF인 경우는 시작하면 안된다.
- [x] req handler에 있는 값값을  초기화 하는 메서드 추가
- [x]  유효성 검사가 필요. CRLF가 연속적으로 올 경우엔 어떻게 처리해야할까?
- [ ] key : value~~~~~~\nvalue 이런 식으로 value 내에 개행이 들어가는 경우는?
- [x]  unvalid protocol case 처리.
- [ ] 필수적으로 알아야 하는 것에 대해 판단하는 녀석. validation 과정이 필요할듯. content length랑 content type이 없으면 에러
- [x] 마지막에 바디 파싱할 때, strlen 을 기준으로 content length와 비교하는 과정으로 파싱을 진행했는데, 0000이 들어가는 경우 문제가 생길수도. char buffer로 한번에 받아서 처리.
