### ISSUE TITLE
Method Processor 개선 및 기능 추가 

### ISSUE THREAD

**Issue by Paul2021-R** [FareWellWebServer/webserv#53]
## description
> 새로운 로직에 맞춰 Method Processor 개선 및 기능 추가 필요 
## todo
- [ ] Method logic 수정(IO 파트) 
- [ ] GET 메서드 수정
- [ ] POST 메서드 작성 
- [ ] DELETE 메서드 작성
