### ISSUE TITLE
ReqHandler_improvement

### ISSUE THREAD

**Issue by SihunLee-1016** [FareWellWebServer/webserv#73]
## description
> 이슈의 목적을 간결하게 서술해주세요
## todo
- [x] /가 연달아 들어오는 경우는 하나로 치환을 해줘야 합니다
- [x] 그것과 entity 관련 헤더가 존재하는데 정작 Entity가 존재하지 않을 때의 예외처리를 하려고 합니다
- [ ] req stage?
- [ ] 프로세스가 진행되다 종료되는 경우 Clear를 해주는 함수를 만들려고 합니다.
- [ ] methord 가 config 내 존재 하는지 확인 필요.
- [ ] uri 에 따라 Redirection 문제 어떻게 처리할 것인이 rfc를 읽고 상의 후 결정해야함.

**Comment by SihunLee-1016** [comment]
여담으로 _ config파일 내 directory list가 On 되어있다면 127.0.0.1:8080/ 이런 식으로 들어온다면 리스트를 전부 출력하는 내용이 있어야 함
